name: CD
on: 
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    create-version-pr-or-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setuo Node Environment
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "npm"
            - name: Install Dependencies
              run: npm ci
            - name: Create version PR or Github Release
              id: changesets
              uses: changesets/action@v1
              with:
                publish: npx changeset tag # creates a release
              env:
                GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
            - run: echo '${{ toJSON(steps.changesets.outputs) }}'