name: Deploy
on:
  workflow_dispatch:
    inputs:
      aws-env:
        description: "AWS Elastic Beanstalk Environment"
        required: true
        default: "gha-nextjs-cicd-staging-env"
        type: string
      github-env:
        description: "Github Environment"
        required: true
        default: "staging"
        type: string
  workflow_call:
    inputs:
      aws-env:
        description: "AWS Elastic Beanstalk Environment"
        required: true
        default: "gha-nextjs-cicd-staging-env"
        type: string
      github-env:
        description: "Github Environment"
        required: true
        default: "staging"
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.aws-env }}-${{ inputs.github-env }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.github-env }}
      # url: "https://${{ steps.get-env-cname.outputs.aws_env_cname }}"
    steps:
      - name: Check ENV
        run: "echo AWS ENV: ${{ inputs.aws-env }} | Github ENV: ${{ inputs.github-env }}"
